### ISSUE TITLE
評価結果の表示の統一

### ISSUE THREAD

**Issue by athos** [t-cool/clojurescript-unraveled#3]
コード中の評価結果の表示が、前半は

```
;; ==> ...
```

となっているのが、後半は

```
;; => ...
```

となっていて統一されていないようです。

原文では後者に統一されているのでそちらに合わせた方が無難に思いますが、何か意図がありますか？

**Comment by t-cool** [comment]
修正しました！
https://github.com/t-cool/clojurescript-unraveled/commit/12264b3f1edd81064fb2b6c2c05573a0dbcc6eb8
