### ISSUE TITLE
インラインに現れるコード片がプロポーショナルフォントで読みづらい

### ISSUE THREAD

**Issue by athos** [t-cool/clojurescript-unraveled#4]
地の文にインラインに現れるコード片がプロポーショナルフォントで書かれていると読みづらいので、 `monospace` に統一したい。

**Comment by t-cool** [comment]
@athos 
すいません。
「地の文にインラインに現れるコード片」と「monospace」が何を指すか分からないので、具体例を挙げていただけないでしょうか？

**Comment by athos** [comment]
分かりにくくてすみません 😓

たとえば、3.7に以下のような文章がありますが：

> 上の例では、シンボル x が (inc 1) の値に束縛されて、シンボル y が x と 1 の合計 (つまり 3 ) に束縛されます。これらの束縛を受けて、 (println "Simple message from the body of a let") と (* x y) が評価されます。

この中のコードに当たる部分(`x` や `(inc i)` 等)が以下のように等幅フォントで表示されてほしいです：

> 上の例では、シンボル `x` が `(inc 1)` の値に束縛されて、シンボル `y` が `x` と 1 の合計 (つまり 3 ) に束縛されます。これらの束縛を受けて、 `(println "Simple message from the body of a let")` と `(* x y)` が評価されます。

具体的な作業としては、コメントアウトされた原文のテキスト中で \` ... \` で括られている箇所に対応する訳文を [`@<code>{ ... }`](https://github.com/kmuto/review/blob/master/doc/format.ja.md#%E6%9C%AC%E6%96%87%E4%B8%AD%E3%81%A7%E3%81%AE%E3%82%BD%E3%83%BC%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%89%E5%BC%95%E7%94%A8) で括っていけばよさそうかなと思います。ただ、一括処理するのは難しそうなので、気づいた部分から徐々に変えていくようなやり方でもいいかもしれません。

**Comment by athos** [comment]
ひとまず #6 で作業を始めたのでそちらで修正を進めていこうと思います。

**Comment by t-cool** [comment]
内容、理解できました！
３章の修正、ありがとうございました。
４章・５章の作業は始められていますか？
もしまだでしたら、こちらのほうで本文を一文ずつ読みながら修正させてもらいます。

**Comment by athos** [comment]
4章、5章についてはまだ着手してません(3章も3.7章までです)。修正お願いできると嬉しいです🙇 

具体的な作業についてですが、「コメントアウトされた原文のテキスト中で〜」と書きましたが、reSTファイルに埋め込まれている原文テキストだと結構 \` \` が落ちてしまってるようなので、原文のオリジナルのAsciiDocを確認した方がよさそうかなと思いました。

**Comment by t-cool** [comment]
では athos さんに修正していただいた commit を merge  しまして、
続きはこちらで修正させてもらいます！

**Comment by athos** [comment]
ありがとうございます 🙏よろしくお願いします。

ちなみに、PRのブランチ(今回の場合は [`feature/markup-inline-code`](https://github.com/t-cool/clojurescript-unraveled/tree/feature/markup-inline-code))は `git pull` してとって来れば追加のコミットをしてpushすることもできます。生煮えのブランチがmasterにマージされてしまうのはあまりよくはない(どこまで作業途中か分かりにくくなる)ので、今後WIPの状態のPRを引き継ぐことがあればそのようにするといいかなと思いました。

**Comment by t-cool** [comment]
インラインコードのマークアップの件、３〜５章を元のAsciiDoc を確認して修正しました。

git fetch の使い方をよく分かっていなかったので、ご助言ありがたいです！
次からそうさせていただきます！
